float64 ned_latitude
float64 ned_longitude
float64 ned_heading

float64 speed

float64 velocity_x
float64 velocity_y
float64 velocity_z

float64 steering_angle
float64 steering_angular_velocity

float64 wheel_velocity_fl
float64 wheel_velocity_fr
float64 wheel_velocity_rl
float64 wheel_velocity_rr

float64 wheel_size_fl
float64 wheel_size_fr
float64 wheel_size_rl
float64 wheel_size_rr

float64 acceleration_left
float64 acceleration_forward

float64 roll
float64 pitch
float64 yaw

float64 wheel_base
float64 curb_weight
